name: Test .Net Core

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2

    - name: Restore NuGet Packages
      run: dotnet restore
 
    - name: Build
      run: dotnet build
      
    - name: Test
      run: dotnet test
      

  record:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Report using branch name (dynamic, use for a pair on each branch)
      run: |
        export GIT_BRANCH_NAME=$(git symbolic-ref --short HEAD)
        export GIT_BRANCH_NAME=$( echo "$GIT_BRANCH_NAME" | sed 's/ /%20/g' )
        curl -X GET ${{ secrets.PUSH_COUNTER_URL }}/record/branch-$GIT_BRANCH_NAME?build=green 
